import XCTest
#if canImport(FoundationNetworking)
import FoundationNetworking   // Linux: URLProtocol, URLSessionConfiguration, HTTPURLResponse
#endif
@testable import RubienCore

/// URLProtocol-based stub for injecting fake HTTP responses.
/// Static state is reset in setUp + tearDown to prevent cross-test leakage.
final class StubURLProtocol: URLProtocol {
    nonisolated(unsafe) static var stubs: [URL: (data: Data, response: HTTPURLResponse)] = [:]
    nonisolated(unsafe) static var failures: [URL: Error] = [:]
    nonisolated(unsafe) static var requests: [URLRequest] = []

    override class func canInit(with request: URLRequest) -> Bool { true }
    override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }

    override func startLoading() {
        guard let url = request.url else {
            client?.urlProtocol(self, didFailWithError: URLError(.badURL))
            return
        }
        StubURLProtocol.requests.append(request)
        if let err = StubURLProtocol.failures[url] {
            client?.urlProtocol(self, didFailWithError: err)
            return
        }
        if let stub = StubURLProtocol.stubs[url] {
            client?.urlProtocol(self, didReceive: stub.response, cacheStoragePolicy: .notAllowed)
            client?.urlProtocol(self, didLoad: stub.data)
            client?.urlProtocolDidFinishLoading(self)
            return
        }
        client?.urlProtocol(self, didFailWithError: URLError(.fileDoesNotExist))
    }

    override func stopLoading() {}

    static func reset() {
        stubs = [:]
        failures = [:]
        requests = []
    }

    static func makeSession() -> URLSession {
        let config = URLSessionConfiguration.ephemeral
        config.protocolClasses = [StubURLProtocol.self]
        return URLSession(configuration: config)
    }

    static func stub(_ urlString: String, status: Int = 200, contentType: String = "text/html", body: String) {
        let url = URL(string: urlString)!
        let response = HTTPURLResponse(
            url: url,
            statusCode: status,
            httpVersion: "HTTP/1.1",
            headerFields: ["Content-Type": contentType]
        )!
        stubs[url] = (body.data(using: .utf8)!, response)
    }
}

private actor CrossrefDOIRecorder {
    private(set) var values: [String] = []

    func record(_ doi: String) {
        values.append(doi)
    }
}

final class PaperURLResolverTests: XCTestCase {

    override func setUp() {
        super.setUp()
        StubURLProtocol.reset()
    }

    override func tearDown() {
        StubURLProtocol.reset()
        super.tearDown()
    }

    private func loadFixture(_ name: String) -> String {
        let url = Bundle.module.url(forResource: "CitationMeta/\(name)", withExtension: "html")!
        return try! String(contentsOf: url, encoding: .utf8)
    }

    func testFetchHTMLAcceptsExplicitHostOutsidePaperRegistry() async throws {
        let url = "https://arxiv.org/abs/2607.14935"
        StubURLProtocol.stub(url, body: "<html><head></head></html>")

        let response = try await PaperURLResolver.fetchHTML(
            url: URL(string: url)!,
            session: StubURLProtocol.makeSession(),
            maxAttempts: 1,
            permittedFinalHosts: ["arxiv.org"]
        )

        XCTAssertEqual(response.finalURL.absoluteString, url)
    }

    // MARK: - OpenReview success path (no DOI)

    func testOpenReviewLandingProducesConferencePaper() async throws {
        StubURLProtocol.stub(
            "https://openreview.net/forum?id=EXAMPLE",
            body: loadFixture("openreview-forum")
        )

        let outcome = try await PaperURLResolver.resolve(
            URL(string: "https://openreview.net/forum?id=EXAMPLE")!,
            session: StubURLProtocol.makeSession()
        )

        XCTAssertEqual(outcome.reference.title, "Attention Is All You Need")
        XCTAssertEqual(outcome.reference.referenceType, .conferencePaper)
        XCTAssertEqual(outcome.reference.metadataSource, .publisherCitationMeta)
        XCTAssertEqual(outcome.reference.url, "https://openreview.net/forum?id=EXAMPLE")
        XCTAssertEqual(outcome.scrapedPDFURL, "https://openreview.net/pdf?id=EXAMPLE")
    }

    // MARK: - APS DOI path (no publisher-page fetch)

    func testAPSAbstractResolvesThroughCrossrefWithoutFetchingPublisherHTML() async throws {
        let input = "https://journals.aps.org/prl/abstract/10.1103/3v91-5pzf"
        let recorder = CrossrefDOIRecorder()
        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                await recorder.record(doi)
                guard doi == "10.1103/3v91-5pzf" else { throw URLError(.badURL) }
                return Reference(
                    title: "Directional Photocurrent Generated by Quantum Interference Control",
                    authors: [AuthorName(given: "Yiming", family: "Gong")],
                    year: 2026,
                    journal: "Physical Review Letters",
                    volume: "137",
                    issue: "3",
                    pages: "036901",
                    doi: doi,
                    url: "https://doi.org/\(doi)"
                )
            }
        )

        XCTAssertTrue(StubURLProtocol.requests.isEmpty, "APS HTML should not be fetched")
        let resolvedDOIs = await recorder.values
        XCTAssertEqual(resolvedDOIs, ["10.1103/3v91-5pzf"])
        XCTAssertEqual(outcome.reference.title, "Directional Photocurrent Generated by Quantum Interference Control")
        XCTAssertEqual(outcome.reference.referenceType, .journalArticle)
        XCTAssertEqual(outcome.reference.url, input)
        XCTAssertEqual(outcome.reference.doi, "10.1103/3v91-5pzf")
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://journals.aps.org/prl/pdf/10.1103/3v91-5pzf"
        )
    }

    func testAPSAcceptedPaperDoesNotInventVersionOfRecordPDF() async throws {
        let input = "https://journals.aps.org/prl/accepted/10.1103/3v91-5pzf"
        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                Reference(
                    title: "Directional Photocurrent Generated by Quantum Interference Control",
                    authors: [AuthorName(given: "Yiming", family: "Gong")],
                    doi: doi
                )
            }
        )

        XCTAssertEqual(outcome.reference.url, input)
        XCTAssertNil(outcome.scrapedPDFURL)
    }

    /// End-to-end PDF-link input: the stored URL is rewritten to the abstract
    /// landing page, CrossRef is called exactly once with the path DOI, and
    /// the sibling /pdf/ URL is surfaced for download.
    func testAPSPDFInputRewritesToAbstractAndSurfacesPDFURL() async throws {
        let input = "https://journals.aps.org/prl/pdf/10.1103/3v91-5pzf"
        let recorder = CrossrefDOIRecorder()
        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                await recorder.record(doi)
                return Reference(
                    title: "Directional Photocurrent Generated by Quantum Interference Control",
                    authors: [AuthorName(given: "Yiming", family: "Gong")],
                    doi: doi
                )
            }
        )

        XCTAssertTrue(StubURLProtocol.requests.isEmpty, "APS HTML should not be fetched")
        let resolvedDOIs = await recorder.values
        XCTAssertEqual(resolvedDOIs, ["10.1103/3v91-5pzf"])
        XCTAssertEqual(
            outcome.reference.url,
            "https://journals.aps.org/prl/abstract/10.1103/3v91-5pzf"
        )
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://journals.aps.org/prl/pdf/10.1103/3v91-5pzf"
        )
    }

    // MARK: - DOI-bearing publisher paths (no publisher-page fetch)

    func testScienceArticleResolvesThroughCrossrefWithoutFetchingPublisherHTML() async throws {
        let input = "https://www.science.org/doi/full/10.1126/sciadv.abn9545"
        let recorder = CrossrefDOIRecorder()
        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                await recorder.record(doi)
                return Reference(
                    title: "Machine learning enables interpretable discovery of innovative polymers",
                    authors: [AuthorName(given: "Jason", family: "Yang")],
                    doi: doi,
                    url: "https://doi.org/\(doi)"
                )
            }
        )

        XCTAssertTrue(StubURLProtocol.requests.isEmpty, "Science HTML should not be fetched")
        let resolvedDOIs = await recorder.values
        XCTAssertEqual(resolvedDOIs, ["10.1126/sciadv.abn9545"])
        XCTAssertEqual(outcome.reference.url, input)
        XCTAssertEqual(outcome.reference.doi, "10.1126/sciadv.abn9545")
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://www.science.org/doi/pdf/10.1126/sciadv.abn9545"
        )
    }

    func testACSArticleResolvesThroughCrossrefWithoutFetchingPublisherHTML() async throws {
        let input = "https://pubs.acs.org/doi/full/10.1021/acscentsci.3c01275"
        let recorder = CrossrefDOIRecorder()
        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                await recorder.record(doi)
                return Reference(
                    title: "Opportunities and Challenges for Machine Learning-Assisted Enzyme Engineering",
                    authors: [AuthorName(given: "Jason", family: "Yang")],
                    doi: doi,
                    url: "https://doi.org/\(doi)"
                )
            }
        )

        XCTAssertTrue(StubURLProtocol.requests.isEmpty, "ACS HTML should not be fetched")
        let resolvedDOIs = await recorder.values
        XCTAssertEqual(resolvedDOIs, ["10.1021/acscentsci.3c01275"])
        XCTAssertEqual(outcome.reference.url, input)
        XCTAssertEqual(outcome.reference.doi, "10.1021/acscentsci.3c01275")
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://pubs.acs.org/doi/pdf/10.1021/acscentsci.3c01275"
        )
    }

    func testDOIPublisherPDFInputRewritesBeforeResolution() async throws {
        let sciencePDF = "https://www.science.org/doi/epdf/10.1126/sciadv.abn9545"
        let outcome = try await PaperURLResolver.resolve(
            URL(string: sciencePDF)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                Reference(
                    title: "Machine learning enables interpretable discovery of innovative polymers",
                    authors: [AuthorName(given: "Jason", family: "Yang")],
                    doi: doi
                )
            }
        )

        XCTAssertTrue(StubURLProtocol.requests.isEmpty, "Science HTML should not be fetched")
        XCTAssertEqual(
            outcome.reference.url,
            "https://www.science.org/doi/10.1126/sciadv.abn9545"
        )
        XCTAssertEqual(outcome.scrapedPDFURL, "https://www.science.org/doi/pdf/10.1126/sciadv.abn9545")
    }

    // MARK: - Astronomy & Astrophysics citation metadata

    func testAANDAArticleResolvesCitationMetadataAndPDF() async throws {
        let input = "https://www.aanda.org/articles/aa/full_html/2026/02/aa57022-25/aa57022-25.html"
        StubURLProtocol.stub(
            input,
            body: """
            <html><head>
              <meta name="citation_journal_title" content="Astronomy &amp; Astrophysics">
              <meta name="citation_publisher" content="EDP Sciences">
              <meta name="citation_author" content="Saurabh Saurabh">
              <meta name="citation_author" content="Hendrik Müller">
              <meta name="citation_title" content="Probing jet base emission of M87* with the 2021 Event Horizon Telescope observations">
              <meta name="citation_publication_date" content="2026/02/01">
              <meta name="citation_volume" content="706">
              <meta name="citation_firstpage" content="A27">
              <meta name="citation_doi" content="10.1051/0004-6361/202557022">
              <meta name="citation_pdf_url" content="https://www.aanda.org/articles/aa/pdf/2026/02/aa57022-25.pdf">
            </head><body></body></html>
            """
        )

        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { _ in throw URLError(.notConnectedToInternet) }
        )

        XCTAssertEqual(StubURLProtocol.requests.map(\.url), [URL(string: input)!])
        XCTAssertEqual(outcome.reference.title, "Probing jet base emission of M87* with the 2021 Event Horizon Telescope observations")
        XCTAssertEqual(outcome.reference.authors.count, 2)
        XCTAssertEqual(outcome.reference.year, 2026)
        XCTAssertEqual(outcome.reference.journal, "Astronomy & Astrophysics")
        XCTAssertEqual(outcome.reference.volume, "706")
        XCTAssertEqual(outcome.reference.pages, "A27")
        XCTAssertEqual(outcome.reference.doi, "10.1051/0004-6361/202557022")
        XCTAssertEqual(outcome.reference.url, input)
        XCTAssertEqual(outcome.reference.referenceType, .journalArticle)
        XCTAssertEqual(outcome.reference.metadataSource, .publisherCitationMeta)
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://www.aanda.org/articles/aa/pdf/2026/02/aa57022-25.pdf"
        )
    }

    // MARK: - Cell Press PII path

    func testCellPressArticleResolvesThroughPubMedWithoutScrapingPublisherHTML() async throws {
        let input = "https://www.cell.com/neuron/fulltext/S0896-6273(26)00414-9?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0896627326004149%3Fshowall%3Dtrue"
        let pii = "S0896-6273(26)00414-9"
        let searchURL = try XCTUnwrap(MetadataFetcher.pubMedSearchURL(forPII: pii))
        StubURLProtocol.stub(
            searchURL.absoluteString,
            contentType: "application/json",
            body: """
            {
              "esearchresult": {
                "count": "1",
                "idlist": ["42392073"]
              }
            }
            """
        )
        let summaryURL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=42392073&retmode=json"
        StubURLProtocol.stub(
            summaryURL,
            contentType: "application/json",
            body: """
            {
              "result": {
                "uids": ["42392073"],
                "42392073": {
                  "title": "Sparse component analysis: A method that uncovers separable computations within neural population activity.",
                  "pubdate": "2026 Jul 2",
                  "source": "Neuron",
                  "authors": [
                    {"name": "Zimnik AJ"},
                    {"name": "Glaser JI"}
                  ],
                  "articleids": [
                    {"idtype": "doi", "value": "10.1016/j.neuron.2026.05.022"}
                  ]
                }
              }
            }
            """
        )
        let recorder = CrossrefDOIRecorder()

        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                await recorder.record(doi)
                throw URLError(.notConnectedToInternet)
            }
        )

        XCTAssertEqual(StubURLProtocol.requests.map(\.url), [searchURL, URL(string: summaryURL)!])
        let resolvedDOIs = await recorder.values
        XCTAssertEqual(resolvedDOIs, ["10.1016/j.neuron.2026.05.022"])
        XCTAssertEqual(outcome.reference.title, "Sparse component analysis: A method that uncovers separable computations within neural population activity")
        XCTAssertEqual(outcome.reference.authors.count, 2)
        XCTAssertEqual(outcome.reference.year, 2026)
        XCTAssertEqual(outcome.reference.journal, "Neuron")
        XCTAssertEqual(outcome.reference.pmid, "42392073")
        XCTAssertEqual(outcome.reference.doi, "10.1016/j.neuron.2026.05.022")
        XCTAssertEqual(
            outcome.reference.url,
            "https://www.cell.com/neuron/fulltext/S0896-6273(26)00414-9"
        )
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://www.cell.com/neuron/pdf/S0896-6273(26)00414-9.pdf"
        )
    }

    func testCellPressFallsBackToLinkingHubAndExactOpenAlexMatch() async throws {
        let input = "https://www.cell.com/joule/fulltext/S2542-4351(26)00214-X"
        let pii = "S2542-4351(26)00214-X"
        let searchURL = try XCTUnwrap(MetadataFetcher.pubMedSearchURL(forPII: pii))
        StubURLProtocol.stub(
            searchURL.absoluteString,
            contentType: "application/json",
            body: #"{"esearchresult":{"count":"0","idlist":[]}}"#
        )
        let linkingHubURL = try XCTUnwrap(PaperURLResolver.cellPressLinkingHubURL(forPII: pii))
        let title = "Prospects for mining critical materials from nontraditional water sources to meet decarbonized energy needs"
        StubURLProtocol.stub(
            linkingHubURL.absoluteString,
            body: "<script>articleName : '\(title)', identifierValue : 'S254243512600214X'</script>"
        )
        let openAlexURL = try XCTUnwrap(MetadataFetcher.openAlexCellPressTitleSearchURL(
            title,
            expectedISSN: "2542-4351",
            assignmentYearSuffix: 26
        ))
        StubURLProtocol.stub(
            openAlexURL.absoluteString,
            contentType: "application/json",
            body: """
            {
              "meta": {"count": 2},
              "results": [
                {
                  "title": "\(title)",
                  "doi": "https://doi.org/10.1016/j.energy.2026.999999",
                  "publication_year": 2026,
                  "authorships": [{"author":{"display_name":"Wrong Author"}}],
                  "primary_location": {"source":{"display_name":"Energy", "issn":["0360-5442"]}},
                  "biblio": {},
                  "type": "article"
                },
                {
                  "title": "\(title)",
                  "doi": "https://doi.org/10.1016/j.joule.2026.102530",
                  "publication_year": 2026,
                  "authorships": [{"author":{"display_name":"Lauren E. McMahon"}}],
                  "primary_location": {"source":{"display_name":"Joule", "issn":["2542-4351"]}},
                  "biblio": {},
                  "type": "article"
                }
              ]
            }
            """
        )
        let recorder = CrossrefDOIRecorder()

        let outcome = try await PaperURLResolver.resolve(
            URL(string: input)!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { doi in
                await recorder.record(doi)
                throw URLError(.notConnectedToInternet)
            }
        )

        XCTAssertEqual(
            StubURLProtocol.requests.map(\.url),
            [searchURL, linkingHubURL, openAlexURL]
        )
        let resolvedDOIs = await recorder.values
        XCTAssertEqual(resolvedDOIs, ["10.1016/j.joule.2026.102530"])
        XCTAssertEqual(outcome.reference.title, title)
        XCTAssertEqual(outcome.reference.journal, "Joule")
        XCTAssertEqual(outcome.reference.year, 2026)
        XCTAssertEqual(outcome.reference.doi, "10.1016/j.joule.2026.102530")
        XCTAssertEqual(outcome.reference.url, input)
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://www.cell.com/joule/pdf/S2542-4351(26)00214-X.pdf"
        )
    }

    func testCellPressOpenAlexFallbackRejectsAmbiguousPIIIdentityMatches() async throws {
        let title = "Editorial"
        let openAlexURL = try XCTUnwrap(MetadataFetcher.openAlexCellPressTitleSearchURL(
            title,
            expectedISSN: "2542-4351",
            assignmentYearSuffix: 26
        ))
        StubURLProtocol.stub(
            openAlexURL.absoluteString,
            contentType: "application/json",
            body: """
            {
              "meta": {"count": 2},
              "results": [
                {
                  "title": "Editorial",
                  "doi": "https://doi.org/10.1016/j.joule.2026.100001",
                  "publication_year": 2026,
                  "primary_location": {"source":{"display_name":"Joule", "issn":["2542-4351"]}}
                },
                {
                  "title": "Editorial",
                  "doi": "https://doi.org/10.1016/j.joule.2026.100002",
                  "publication_year": 2026,
                  "primary_location": {"source":{"display_name":"Joule", "issn_l":"2542-4351"}}
                }
              ]
            }
            """
        )

        let result = try await MetadataFetcher.fetchFromOpenAlexByExactTitle(
            title,
            expectedISSN: "2542-4351",
            assignmentYearSuffix: 26,
            session: StubURLProtocol.makeSession()
        )

        XCTAssertNil(result)
    }

    func testCellPressOpenAlexFallbackUsesDOIAssignmentYearAcrossPublicationBoundary() async throws {
        let title = "Year-boundary Cell article"
        let openAlexURL = try XCTUnwrap(MetadataFetcher.openAlexCellPressTitleSearchURL(
            title,
            expectedISSN: "2542-4351",
            assignmentYearSuffix: 25
        ))
        StubURLProtocol.stub(
            openAlexURL.absoluteString,
            contentType: "application/json",
            body: """
            {
              "meta": {"count": 2},
              "results": [
                {
                  "title": "Year-boundary Cell article",
                  "doi": "https://doi.org/10.1016/j.joule.2024.999999",
                  "publication_year": 2026,
                  "primary_location": {"source":{"display_name":"Joule", "issn":["2542-4351"]}}
                },
                {
                  "title": "Year-boundary Cell article",
                  "doi": "https://doi.org/10.1016/j.joule.2025.102310",
                  "publication_year": 2026,
                  "primary_location": {"source":{"display_name":"Joule", "issn":["2542-4351"]}}
                }
              ]
            }
            """
        )

        let result = try await MetadataFetcher.fetchFromOpenAlexByExactTitle(
            title,
            expectedISSN: "2542-4351",
            assignmentYearSuffix: 25,
            session: StubURLProtocol.makeSession()
        )

        XCTAssertEqual(result?.doi, "10.1016/j.joule.2025.102310")
        XCTAssertEqual(result?.year, 2026)
    }

    func testCellPressLinkingHubTitleDecodesEscapedApostropheAndEntities() throws {
        let html = #"<script>articleName : 'Earth\'s &amp; future'</script>"#
        XCTAssertEqual(
            PaperURLResolver.parseCellPressLinkingHubTitle(Data(html.utf8)),
            "Earth's & future"
        )
    }

    // MARK: - Content-Type rejection

    func testNonHTMLContentTypeRejected() async {
        StubURLProtocol.stub(
            "https://openreview.net/forum?id=EXAMPLE",
            contentType: "application/pdf",
            body: ""
        )

        do {
            _ = try await PaperURLResolver.resolve(
                URL(string: "https://openreview.net/forum?id=EXAMPLE")!,
                session: StubURLProtocol.makeSession()
            )
            XCTFail("Expected unexpectedContentType")
        } catch PaperURLResolver.ResolveError.unexpectedContentType {
            // expected
        } catch {
            XCTFail("Wrong error type: \(error)")
        }
    }

    // MARK: - Strong evidence gate (paywall)

    func testInsufficientCitationMetaRejected() async {
        // Stub at the canonical URL (no www.) since the resolver fetches the
        // canonicalized form, not the original input.
        StubURLProtocol.stub(
            "https://sciencedirect.com/science/article/pii/SXXXX",
            body: loadFixture("paywall-login-page")
        )

        do {
            _ = try await PaperURLResolver.resolve(
                URL(string: "https://www.sciencedirect.com/science/article/pii/SXXXX")!,
                session: StubURLProtocol.makeSession()
            )
            XCTFail("Expected insufficientMetadata")
        } catch PaperURLResolver.ResolveError.insufficientMetadata {
            // expected
        } catch {
            XCTFail("Wrong error type: \(error)")
        }
    }

    // MARK: - CVF citation_* path

    func testCVFLandingExtractsFromCitationMeta() async throws {
        let url = "https://openaccess.thecvf.com/content/CVPR2025/html/Wang_VGGT_Visual_Geometry_Grounded_Transformer_CVPR_2025_paper.html"
        StubURLProtocol.stub(url, body: loadFixture("cvf-paper"))

        let outcome = try await PaperURLResolver.resolve(
            URL(string: url)!,
            session: StubURLProtocol.makeSession()
        )

        XCTAssertEqual(outcome.reference.title, "VGGT: Visual Geometry Grounded Transformer")
        XCTAssertEqual(outcome.reference.referenceType, .conferencePaper)
        XCTAssertEqual(outcome.reference.metadataSource, .cvfOpenAccess)
        XCTAssertEqual(outcome.reference.authors.count, 6)
        XCTAssertEqual(outcome.reference.authors.first?.family, "Wang")
        XCTAssertEqual(outcome.reference.year, 2025)
        XCTAssertEqual(outcome.reference.pages, "5294-5306")
        XCTAssertEqual(outcome.scrapedPDFURL, "https://openaccess.thecvf.com/content/CVPR2025/papers/Wang_VGGT_Visual_Geometry_Grounded_Transformer_CVPR_2025_paper.pdf")
    }

    // MARK: - eLife official API path

    func testELifeArticleResolvesMetadataAndPDFThroughOfficialAPI() async throws {
        StubURLProtocol.stub(
            "https://api.elifesciences.org/articles/29515",
            contentType: "application/vnd.elife.article-vor+json; version=8",
            body: """
            {
              "status": "vor",
              "id": "29515",
              "version": 1,
              "type": "research-article",
              "doi": "10.7554/eLife.29515",
              "title": "Theta-burst microstimulation in the human entorhinal area improves memory specificity",
              "published": "2017-10-24T00:00:00Z",
              "volume": 6,
              "elocationId": "e29515",
              "pdf": "https://cdn.elifesciences.org/articles/29515/elife-29515-v1.pdf",
              "abstract": {
                "content": [
                  {"type": "paragraph", "text": "The <i>hippocampus</i> is critical for episodic memory."}
                ]
              },
              "authors": [
                {"type": "person", "name": {"index": "Titiz, Ali S", "preferred": "Ali S Titiz"}},
                {"type": "person", "name": {"index": "Hill, Michael R H", "preferred": "Michael R H Hill"}}
              ]
            }
            """
        )

        let outcome = try await PaperURLResolver.resolve(
            URL(string: "https://www.elifesciences.org/articles/29515.pdf")!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { _ in throw URLError(.notConnectedToInternet) }
        )

        XCTAssertEqual(outcome.reference.title, "Theta-burst microstimulation in the human entorhinal area improves memory specificity")
        XCTAssertEqual(outcome.reference.authors.count, 2)
        XCTAssertEqual(outcome.reference.authors[0], AuthorName(given: "Ali S", family: "Titiz"))
        XCTAssertEqual(outcome.reference.year, 2017)
        XCTAssertEqual(outcome.reference.journal, "eLife")
        XCTAssertEqual(outcome.reference.volume, "6")
        XCTAssertEqual(outcome.reference.pages, "e29515")
        XCTAssertEqual(outcome.reference.doi, "10.7554/eLife.29515")
        XCTAssertEqual(outcome.reference.url, "https://elifesciences.org/articles/29515")
        XCTAssertEqual(outcome.reference.abstract, "The hippocampus is critical for episodic memory.")
        XCTAssertEqual(outcome.reference.referenceType, .journalArticle)
        XCTAssertEqual(outcome.reference.metadataSource, .publisherCitationMeta)
        XCTAssertEqual(outcome.scrapedPDFURL, "https://cdn.elifesciences.org/articles/29515/elife-29515-v1.pdf")
        XCTAssertNil(
            StubURLProtocol.requests.first?.value(forHTTPHeaderField: "Accept"),
            "eLife rejects generic JSON Accept headers with HTTP 406"
        )
    }

    func testELifeGroupAuthorIsPreserved() async throws {
        StubURLProtocol.stub(
            "https://api.elifesciences.org/articles/99998",
            contentType: "application/vnd.elife.article-rp+json; version=8",
            body: """
            {
              "id": "99998",
              "title": "A consortium study",
              "published": "2026-01-02T00:00:00Z",
              "authors": [
                {"type": "group", "name": "The Example Research Consortium"}
              ]
            }
            """
        )

        let outcome = try await PaperURLResolver.resolve(
            URL(string: "https://elifesciences.org/articles/99998")!,
            session: StubURLProtocol.makeSession()
        )

        XCTAssertEqual(
            outcome.reference.authors,
            [AuthorName(given: "", family: "The Example Research Consortium")]
        )
    }

    func testELifeRejectsUnexpectedPDFHostFromAPI() async throws {
        StubURLProtocol.stub(
            "https://api.elifesciences.org/articles/99999",
            contentType: "application/vnd.elife.article-vor+json; version=8",
            body: """
            {
              "id": "99999",
              "title": "An article with an unsafe PDF URL",
              "published": "2026-01-02T00:00:00Z",
              "pdf": "https://downloads.example.com/article.pdf",
              "authors": [
                {"type": "person", "name": {"index": "Smith, Jane", "preferred": "Jane Smith"}}
              ]
            }
            """
        )

        let outcome = try await PaperURLResolver.resolve(
            URL(string: "https://elifesciences.org/articles/99999")!,
            session: StubURLProtocol.makeSession()
        )

        XCTAssertNil(outcome.scrapedPDFURL)
    }

    func testELifeRejectsNonJSONMediaType() async {
        StubURLProtocol.stub(
            "https://api.elifesciences.org/articles/99997",
            contentType: "text/notjson",
            body: #"{"id":"99997","title":"Not actually JSON media"}"#
        )

        do {
            _ = try await PaperURLResolver.resolve(
                URL(string: "https://elifesciences.org/articles/99997")!,
                session: StubURLProtocol.makeSession()
            )
            XCTFail("Expected unexpectedContentType")
        } catch PaperURLResolver.ResolveError.unexpectedContentType(let contentType) {
            XCTAssertEqual(contentType, "text/notjson")
        } catch {
            XCTFail("Wrong error type: \(error)")
        }
    }

    // MARK: - eNeuro citation-meta path

    func testENeuroLongURLResolvesFromCanonicalLandingPage() async throws {
        let canonicalURL = "https://www.eneuro.org/content/9/2/ENEURO.0361-21.2022"
        StubURLProtocol.stub(
            canonicalURL,
            body: """
            <html><head>
            <meta name="citation_title" content="Neurophysiological Evidence for Cognitive Map Formation during Sequence Learning">
            <meta name="citation_author" content="Jennifer Stiso">
            <meta name="citation_author" content="Christopher W. Lynn">
            <meta name="citation_journal_title" content="eNeuro">
            <meta name="citation_publisher" content="Society for Neuroscience">
            <meta name="citation_publication_date" content="2022/03/01">
            <meta name="citation_volume" content="9">
            <meta name="citation_issue" content="2">
            <meta name="citation_doi" content="10.1523/ENEURO.0361-21.2022">
            <meta name="citation_pdf_url" content="https://www.eneuro.org/content/eneuro/9/2/ENEURO.0361-21.2022.full.pdf">
            </head></html>
            """
        )

        let outcome = try await PaperURLResolver.resolve(
            URL(string: "https://www.eneuro.org/content/9/2/ENEURO.0361-21.2022.long")!,
            session: StubURLProtocol.makeSession(),
            crossrefFetcher: { _ in throw URLError(.notConnectedToInternet) }
        )

        XCTAssertEqual(outcome.reference.title, "Neurophysiological Evidence for Cognitive Map Formation during Sequence Learning")
        XCTAssertEqual(outcome.reference.authors.map(\.family), ["Stiso", "Lynn"])
        XCTAssertEqual(outcome.reference.year, 2022)
        XCTAssertEqual(outcome.reference.journal, "eNeuro")
        XCTAssertEqual(outcome.reference.volume, "9")
        XCTAssertEqual(outcome.reference.issue, "2")
        XCTAssertEqual(outcome.reference.doi, "10.1523/ENEURO.0361-21.2022")
        XCTAssertEqual(outcome.reference.publisher, "Society for Neuroscience")
        XCTAssertEqual(outcome.reference.url, canonicalURL)
        XCTAssertEqual(outcome.reference.referenceType, .journalArticle)
        XCTAssertEqual(outcome.reference.metadataSource, .publisherCitationMeta)
        XCTAssertEqual(
            outcome.scrapedPDFURL,
            "https://www.eneuro.org/content/eneuro/9/2/ENEURO.0361-21.2022.full.pdf"
        )
        XCTAssertEqual(StubURLProtocol.requests.map(\.url), [URL(string: canonicalURL)!])
    }

    // MARK: - Canonical Reference.url after canonicalization

    func testCanonicalURLOnReference() async throws {
        StubURLProtocol.stub(
            "https://nature.com/articles/foo",
            body: """
            <html><head>
            <meta name="citation_title" content="Nature Paper">
            <meta name="citation_author" content="Smith, J.">
            <meta name="citation_journal_title" content="Nature">
            <meta name="citation_publication_date" content="2024">
            </head></html>
            """
        )

        let outcome = try await PaperURLResolver.resolve(
            URL(string: "HTTPS://WWW.NATURE.COM/articles/foo")!,
            session: StubURLProtocol.makeSession()
        )

        // Canonical: lowercase scheme + host, no www.
        XCTAssertEqual(outcome.reference.url, "https://nature.com/articles/foo")
    }

    // MARK: - No-author safeguard

    func testNoAuthorsReturnsCandidate() async {
        // Hypothetical: citation_title + citation_doi only, no citation_author.
        // CrossRef stub will also fail (no stub registered for crossref endpoint).
        StubURLProtocol.stub(
            "https://ieeexplore.ieee.org/document/1234",
            body: """
            <html><head>
            <meta name="citation_title" content="IEEE Doc Without Authors">
            <meta name="citation_doi" content="10.1109/foo.bar.99999999">
            <meta name="citation_publication_date" content="2024">
            </head></html>
            """
        )

        do {
            _ = try await PaperURLResolver.resolve(
                URL(string: "https://ieeexplore.ieee.org/document/1234")!,
                session: StubURLProtocol.makeSession(),
                crossrefFetcher: { _ in throw URLError(.notConnectedToInternet) }
            )
            XCTFail("Expected noAuthorsAvailable")
        } catch PaperURLResolver.ResolveError.noAuthorsAvailable(let partialRef, _) {
            // Verify the payload carries the partial Reference so the caller
            // can build a CandidateEnvelope from it.
            XCTAssertEqual(partialRef.title, "IEEE Doc Without Authors")
            XCTAssertEqual(partialRef.doi, "10.1109/foo.bar.99999999")
            XCTAssertTrue(partialRef.authors.isEmpty)
        } catch {
            XCTFail("Wrong error type: \(error)")
        }
    }

    // MARK: - HTTP 503 retried

    func testHTTPServerErrorRetries() async throws {
        // First request 503, second 200 — needs a counter-based stub.
        // Use a custom URLProtocol subclass for this test:
        final class CountingStub: URLProtocol {
            nonisolated(unsafe) static var attemptCount = 0
            nonisolated(unsafe) static var html = ""
            override class func canInit(with request: URLRequest) -> Bool { true }
            override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }
            override func startLoading() {
                Self.attemptCount += 1
                let url = request.url!
                if Self.attemptCount == 1 {
                    let r = HTTPURLResponse(url: url, statusCode: 503, httpVersion: "HTTP/1.1", headerFields: ["Content-Type": "text/html"])!
                    client?.urlProtocol(self, didReceive: r, cacheStoragePolicy: .notAllowed)
                    client?.urlProtocolDidFinishLoading(self)
                } else {
                    let r = HTTPURLResponse(url: url, statusCode: 200, httpVersion: "HTTP/1.1", headerFields: ["Content-Type": "text/html"])!
                    client?.urlProtocol(self, didReceive: r, cacheStoragePolicy: .notAllowed)
                    client?.urlProtocol(self, didLoad: Self.html.data(using: .utf8)!)
                    client?.urlProtocolDidFinishLoading(self)
                }
            }
            override func stopLoading() {}
        }

        CountingStub.attemptCount = 0
        CountingStub.html = loadFixture("openreview-forum")
        let config = URLSessionConfiguration.ephemeral
        config.protocolClasses = [CountingStub.self]
        let session = URLSession(configuration: config)

        let outcome = try await PaperURLResolver.resolve(
            URL(string: "https://openreview.net/forum?id=EXAMPLE")!,
            session: session
        )
        XCTAssertEqual(CountingStub.attemptCount, 2)
        XCTAssertEqual(outcome.reference.title, "Attention Is All You Need")
    }

    // MARK: - HTTP 404 does not retry

    func testHTTP404DoesNotRetry() async {
        StubURLProtocol.stub("https://openreview.net/forum?id=DEAD", status: 404, body: "")

        do {
            _ = try await PaperURLResolver.resolve(
                URL(string: "https://openreview.net/forum?id=DEAD")!,
                session: StubURLProtocol.makeSession()
            )
            XCTFail("Expected fetchFailed")
        } catch PaperURLResolver.ResolveError.fetchFailed(let status, _) {
            XCTAssertEqual(status, 404)
        } catch {
            XCTFail("Wrong error: \(error)")
        }
    }
}
