#!/usr/bin/env bash
# Regenerates Sources/RubienCLI/GeneratedVersion.swift from VERSION + BUILD.txt.
# The output file is CHECKED IN; CI (.github/workflows/ci.yml) fails if it drifts.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
BUILD="$(tr -d '[:space:]' < "$ROOT/BUILD.txt")"
OUT="$ROOT/Sources/RubienCLI/GeneratedVersion.swift"
cat > "$OUT" <<EOF
// GENERATED by scripts/generate-cli-version.sh from VERSION + BUILD.txt.
// Do not edit by hand. CI fails if this drifts from those files.
enum RubienCLIVersion {
    static let marketing = "$VERSION"
    static let build = $BUILD
}
EOF
echo "wrote $OUT (marketing=$VERSION build=$BUILD)"
