// GENERATED by scripts/generate-cli-version.sh from VERSION + BUILD.txt.
// Do not edit by hand. CI fails if this drifts from those files.
enum RubienCLIVersion {
    static let marketing = "0.7.0"
    static let build = 38
}
